---
- hosts: all
  tasks:
  - name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
    win_chocolatey:
      name: chocolatey

  - name: Install webpicmd
    win_chocolatey:
      name: webpicmd
      version: '7.1.50430.20141001'
      source: https://community.chocolatey.org/api/v2/
      state: present
