---
- hosts: all
  tasks:

  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\install\sql
      state: directory

  - name: Copy SQL Install file local to Remote Host
    ansible.windows.win_copy:
      src: SQLEXPR_x64_ENU.exe
      dest: C:\install
        
  - name: Prepare SQL Setup file on remote host
    ansible.windows.win_command:
      cmd: C:\install\SQLEXPR_x64_ENU.exe /q /x:C:\install\sql\SQLEXPR_2019

  - name: Copy SQL config file local to Remote Host
    ansible.windows.win_copy:
      src: ConfigurationFile.ini
      dest: C:\install\sql\SQLEXPR_2019

  - name: Install 7zip from a network share with specific credentials
    ansible.windows.win_package:
      path: C:\install\SQL\SQLEXPR_2019\Setup.exe
      arguments: /ACtion=install /Q /IAcceptSQLServerLicenseTerms=true /INSTANCENAME=SQLEXPRESS /ConfigurationFile=C:\install\sql\myconf.ini
      state: present
    become: yes
    become_method: runas
    become_user: malon
    become_flags: logon_type=interactive logon_flags=with_profile
    vars:
      become_password: Sauber88$

