---
- hosts: all
  tasks:

  - name: Install Thunderbird 
    ansible.windows.win_powershell:
      script: |
        Disable-WindowsOptionalFeature -FeatureName Internet-Explorer-Optional-amd64 –Online -NoRestart

  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot:
