---
- hosts: all
  tasks:

  - name: Define when to enable Verbose/Debug output
    ansible.windows.win_powershell:
      script: |
        if ($Ansible.Verbosity -ge 3) {
            $VerbosePreference = "Continue"
        }
        if ($Ansible.Verbosity -eq 5) {
            $DebugPreference = "Continue"
        }
        Write-Output "Hello World!"
        Write-Verbose "Hello World!"
        Write-Debug "Hello World!
