---
- hosts: all



  tasks:
     
  - name: Get facts
    ansible.windows.setup:

  - name: Warn logged in users of impending upgrade (note use of async to stop the module from waiting until notification expires).
    community.windows.win_toast:
      expire: 60
      title: System Upgrade Notification
      msg: Automated upgrade about to start.  Please save your work and log off before hihi
    async: 60
    poll: 0
