---
- hosts: all
  tasks:


  - name: Remove Notpad++ an 7zip with remote shell
    ansible.windows.win_shell: powershell.exe Invoke-Command -ScriptBlock {Start-Process -FilePath "C:\Program Files\7-Zipi\Uninstall.exe" -ArgumentList “/S” -Wait}
